#!/bin/bash

# patch file on stdin
# feedback goes to stdout
# stderr is stderr
# fds 3 and 4 are NOT to be used -- bash will use them itself
# fd 7: the dirfd
# fd 8; the audit log

# source our helper funcs
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" )" )"/funcs.sh

#echo "HOME is $HOME" 1>&2
#whoami 1>&2
#echo "/proc/self/fd/8 is `readlink -f /proc/self/fd/8 2>&1`" 1>&2
#echo "COLUMNS is $COLUMNS" 1>&2

case "$1" in
    (1|2|3|4|5|6)
        proj_n_feedback $1
    ;;
    (*)
       echo "Eep! I haven't got as far as helping with project $1 yet"
    ;;
esac
